"""One-time, guarded restoration of recurring-invoice templates from a local
recovery archive (the format produced by export_invoice_reset_archive.py).

Scope is deliberately narrow: this script reads ONLY the archive's top-level
"recurring_invoices" array. No other archive section (invoices, invoice
files/PDFs, extraction results, activity/audit logs, credit notes, approval
requests, etc.) is ever loaded, inspected, or imported by this script.

Default mode is a read-only preview — nothing is written to the database
unless --apply is passed explicitly. Restored rows are inserted directly as
RecurringInvoice records in one all-or-nothing transaction. This script
deliberately never calls
app.services.recurring_invoice_service.create_recurring_invoice(): that
service always resets occurrence_count to 0 and, when a template's first
due date is not in the future, immediately generates a historic invoice —
both are wrong for a restore. No invoice is ever generated by this script.

Restored templates always get expense_nature="invoice" — the archive
predates that column, so there is no original value to preserve.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Optional

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.db.database import SessionLocal
from app.models.models import Entity, Project, RecurringInvoice, User
from app.schemas.recurring_invoice import VALID_FREQUENCIES

RESTORED_EXPENSE_NATURE = "invoice"

REQUIRED_STRING_FIELDS = ("supplier_name_raw", "invoice_number_base")
REQUIRED_DATE_FIELDS = ("start_date", "next_due_date")
OPTIONAL_DATE_FIELDS = ("end_date",)
OPTIONAL_DATETIME_FIELDS = ("last_generated_at", "created_at", "updated_at")


@dataclass
class TargetState:
    entities_by_id: dict
    projects_by_id: dict
    users_by_id: dict
    existing_recurring_keys: set


@dataclass
class RecordResult:
    index: int
    source_id: Any
    supplier_name_raw: str
    status: str  # "ready", "duplicate", or "rejected"
    reject_reasons: list = field(default_factory=list)
    warnings: list = field(default_factory=list)
    insert_kwargs: Optional[dict] = None


def load_target_state(db) -> TargetState:
    entities_by_id = {e.id: e.name for e in db.query(Entity).all()}
    projects_by_id = {p.id: p.name for p in db.query(Project).all()}
    users_by_id = {u.id: u.full_name for u in db.query(User).all()}
    existing_recurring_keys = {
        _duplicate_key(r.supplier_name_raw, r.invoice_number_base, r.paying_entity_id)
        for r in db.query(RecurringInvoice).all()
    }
    return TargetState(entities_by_id, projects_by_id, users_by_id, existing_recurring_keys)


def _duplicate_key(supplier_name_raw, invoice_number_base, paying_entity_id):
    return (
        (supplier_name_raw or "").strip().lower(),
        (invoice_number_base or "").strip().lower(),
        paying_entity_id,
    )


def _parse_date(value):
    if value in (None, ""):
        return None, None
    try:
        return date.fromisoformat(value), None
    except (ValueError, TypeError):
        return None, f"unparseable date {value!r}"


def _parse_datetime(value):
    if value in (None, ""):
        return None, None
    try:
        return datetime.fromisoformat(value), None
    except (ValueError, TypeError):
        return None, f"unparseable datetime {value!r}"


def _parse_amount(value):
    if value in (None, ""):
        return None, None
    try:
        return Decimal(str(value)), None
    except (InvalidOperation, ValueError, TypeError):
        return None, f"unparseable amount {value!r}"


def _resolve_reference(ref_id, archived_name, target_names_by_id, kind: str):
    """Check an FK reference against the target DB. Returns a list of
    messages: a rejection-worthy message if the id doesn't exist at all, or
    an informational warning if the id exists but its name has since
    changed (str) — a signal the id may have been reassigned to a different
    record, not just renamed."""
    if ref_id is None:
        return [], []
    if ref_id not in target_names_by_id:
        return [f"{kind} id {ref_id} not found in target database"], []
    current_name = target_names_by_id[ref_id]
    if archived_name and current_name != archived_name:
        return [], [f"{kind} id {ref_id} name changed: archived {archived_name!r}, now {current_name!r}"]
    return [], []


def _resolve_created_by(record, target: TargetState, fallback_created_by):
    """created_by is NOT NULL on RecurringInvoice, and misattributing it
    matters (it's an accountability field) — so unlike entity/project, an id
    that exists but whose name no longer matches the archive is treated the
    same as a missing id, not just a warning: the numeric id may have been
    reassigned to a different person entirely."""
    cb_id = record.get("created_by")
    cb_name = record.get("created_by_name")

    if cb_id is not None and cb_id in target.users_by_id:
        current_name = target.users_by_id[cb_id]
        if not cb_name or current_name == cb_name:
            return cb_id, []

    if fallback_created_by is not None and fallback_created_by in target.users_by_id:
        return fallback_created_by, [
            f"created_by {cb_id!r} ({cb_name!r}) missing or reassigned in target — "
            f"using --fallback-created-by {fallback_created_by} instead"
        ]

    return None, [
        f"created_by {cb_id!r} ({cb_name!r}) missing or reassigned in target and no "
        f"--fallback-created-by supplied"
    ]


def evaluate_record(index: int, record: dict, target: TargetState, fallback_created_by) -> RecordResult:
    reject_reasons: list = []
    warnings: list = []

    for field_name in REQUIRED_STRING_FIELDS:
        if not (record.get(field_name) or "").strip():
            reject_reasons.append(f"missing required field {field_name!r}")

    frequency = record.get("frequency")
    if frequency not in VALID_FREQUENCIES:
        reject_reasons.append(f"invalid frequency {frequency!r}")

    gross_amount, err = _parse_amount(record.get("gross_amount"))
    if err:
        reject_reasons.append(f"gross_amount: {err}")
    elif gross_amount is None:
        reject_reasons.append("missing required field 'gross_amount'")
    elif gross_amount <= 0:
        reject_reasons.append(f"gross_amount must be greater than 0, got {gross_amount}")

    vat_amount, err = _parse_amount(record.get("vat_amount"))
    if err:
        reject_reasons.append(f"vat_amount: {err}")

    net_amount, err = _parse_amount(record.get("net_amount"))
    if err:
        reject_reasons.append(f"net_amount: {err}")

    parsed_dates = {}
    for field_name in REQUIRED_DATE_FIELDS:
        value, err = _parse_date(record.get(field_name))
        if err:
            reject_reasons.append(f"{field_name}: {err}")
        elif value is None:
            reject_reasons.append(f"missing required field {field_name!r}")
        parsed_dates[field_name] = value

    for field_name in OPTIONAL_DATE_FIELDS:
        value, err = _parse_date(record.get(field_name))
        if err:
            warnings.append(f"{field_name}: {err} — treated as not set")
        parsed_dates[field_name] = value

    parsed_datetimes = {}
    for field_name in OPTIONAL_DATETIME_FIELDS:
        value, err = _parse_datetime(record.get(field_name))
        if err:
            warnings.append(f"{field_name}: {err} — treated as not set")
        parsed_datetimes[field_name] = value

    project_id = record.get("project_id")
    if project_id is None:
        reject_reasons.append("missing required field 'project_id'")
    else:
        reasons, warns = _resolve_reference(project_id, record.get("project_name"), target.projects_by_id, "project")
        reject_reasons += reasons
        warnings += warns

    paying_entity_id = record.get("paying_entity_id")
    reasons, warns = _resolve_reference(paying_entity_id, record.get("entity_name"), target.entities_by_id, "entity")
    reject_reasons += reasons
    warnings += warns

    created_by, cb_messages = _resolve_created_by(record, target, fallback_created_by)
    if created_by is None:
        reject_reasons += cb_messages
    else:
        warnings += cb_messages

    duplicate_key = _duplicate_key(record.get("supplier_name_raw"), record.get("invoice_number_base"), paying_entity_id)
    is_duplicate = duplicate_key in target.existing_recurring_keys

    result = RecordResult(
        index=index,
        source_id=record.get("id"),
        supplier_name_raw=record.get("supplier_name_raw") or "(no supplier)",
        status="ready",
        reject_reasons=reject_reasons,
        warnings=warnings,
    )

    if reject_reasons:
        result.status = "rejected"
        return result

    if is_duplicate:
        result.status = "duplicate"
        result.warnings.append(
            "matches an existing target recurring template on (supplier, invoice_number_base, entity) — skipped by default"
        )
        return result

    result.insert_kwargs = dict(
        supplier_name_raw=record.get("supplier_name_raw"),
        paying_entity_raw=record.get("paying_entity_raw"),
        paying_entity_id=paying_entity_id,
        project_id=project_id,
        invoice_number_base=record.get("invoice_number_base"),
        gross_amount=gross_amount,
        vat_amount=vat_amount,
        net_amount=net_amount,
        currency=record.get("currency") or "GBP",
        description=record.get("description"),
        frequency=frequency,
        frequency_interval=record.get("frequency_interval") or 1,
        day_of_month=record.get("day_of_month"),
        start_date=parsed_dates["start_date"],
        end_date=parsed_dates.get("end_date"),
        max_occurrences=record.get("max_occurrences"),
        occurrence_count=record.get("occurrence_count") or 0,
        next_due_date=parsed_dates["next_due_date"],
        last_generated_at=parsed_datetimes.get("last_generated_at"),
        is_active=bool(record.get("is_active")),
        created_by=created_by,
        expense_nature=RESTORED_EXPENSE_NATURE,
    )
    if parsed_datetimes.get("created_at") is not None:
        result.insert_kwargs["created_at"] = parsed_datetimes["created_at"]
    if parsed_datetimes.get("updated_at") is not None:
        result.insert_kwargs["updated_at"] = parsed_datetimes["updated_at"]

    return result


def print_preview(records, results, archive_path) -> None:
    active_count = sum(1 for r in records if r.get("is_active"))
    print("=== RECURRING TEMPLATE RESTORE PREVIEW ===")
    print(f"Archive: {archive_path}")
    print(f"Source template count: {len(records)}")
    print(f"  active:   {active_count}")
    print(f"  inactive: {len(records) - active_count}")

    print("\nPer-template detail (as recorded in the archive):")
    for record, result in zip(records, results):
        print(
            f"  [{result.index}] {record.get('supplier_name_raw')!r} "
            f"| entity={record.get('paying_entity_id')} {record.get('entity_name')!r} "
            f"| project={record.get('project_id')} {record.get('project_name')!r} "
            f"| {record.get('currency')} {record.get('gross_amount')} "
            f"| {record.get('frequency')} "
            f"| occurrences={record.get('occurrence_count')} "
            f"| next_due={record.get('next_due_date')} "
            f"| active={record.get('is_active')}"
        )

    warned = [r for r in results if r.warnings]
    if warned:
        print("\nReference/data warnings (informational — record still eligible unless also rejected):")
        for r in warned:
            for message in r.warnings:
                print(f"  [{r.index}] {r.supplier_name_raw!r}: {message}")

    duplicates = [r for r in results if r.status == "duplicate"]
    if duplicates:
        print("\nDuplicate candidates (already present in target recurring_invoices — skipped by default):")
        for r in duplicates:
            print(f"  [{r.index}] {r.supplier_name_raw!r}")

    rejected = [r for r in results if r.status == "rejected"]
    if rejected:
        print("\nRecords that would be SKIPPED / REJECTED:")
        for r in rejected:
            for reason in r.reject_reasons:
                print(f"  [{r.index}] {r.supplier_name_raw!r}: {reason}")

    ready = [r for r in results if r.status == "ready"]
    print(f"\nReady to import: {len(ready)} of {len(records)} "
          f"({len(duplicates)} duplicate, {len(rejected)} rejected)")


def run_preview(db, records, fallback_created_by):
    """Read-only preview/validation phase. Runs entirely on the given
    session and never writes — safe to call with a session the caller
    intends to close or discard afterward."""
    target = load_target_state(db)
    return [
        evaluate_record(i, record, target, fallback_created_by)
        for i, record in enumerate(records, start=1)
    ]


def apply_ready_records(ready) -> None:
    """Insert every ready record in one all-or-nothing transaction, using a
    brand-new session created just for this write.

    Deliberately does NOT reuse the session that ran the preview/validation
    reads: SQLAlchemy sessions auto-begin a transaction on first query, and
    calling `with db.begin()` on a session that already has one open raises
    "InvalidRequestError: A transaction is already begun on this Session"
    (the same failure the invoice-reset script hit). A fresh session has no
    prior transaction, so this can't happen regardless of what the read
    phase did or how long it ran.
    """
    if not ready:
        return
    write_db = SessionLocal()
    try:
        with write_db.begin():
            for r in ready:
                write_db.add(RecurringInvoice(**r.insert_kwargs))
    finally:
        write_db.close()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="One-time restore of recurring-invoice templates from a local recovery "
                     "archive's 'recurring_invoices' section only. Preview (read-only) by default.",
    )
    parser.add_argument("archive_path", help="Path to the local recovery archive JSON file.")
    parser.add_argument(
        "--apply", action="store_true",
        help="Insert the templates marked READY in the preview. Without this flag nothing is written.",
    )
    parser.add_argument(
        "--fallback-created-by", type=int, default=None, metavar="USER_ID",
        help="Target user id to attribute a restored template to when its archived created_by "
             "user is missing from the target database or that id now belongs to someone else.",
    )
    args = parser.parse_args()

    archive_path = Path(args.archive_path)
    if not archive_path.is_file():
        parser.error(f"Archive file not found: {archive_path}")

    with archive_path.open("r", encoding="utf-8") as f:
        archive = json.load(f)

    records = archive.get("recurring_invoices")
    if records is None:
        parser.error("Archive has no top-level 'recurring_invoices' array — nothing to restore.")

    # Preview/validation runs on its own session, fully closed before any
    # write session is opened — see apply_ready_records() for why.
    read_db = SessionLocal()
    try:
        results = run_preview(read_db, records, args.fallback_created_by)
    finally:
        read_db.close()

    print_preview(records, results, archive_path)

    if not args.apply:
        print(
            "\nDRY RUN ONLY — no database rows were changed and no invoices were generated. "
            "Re-run with --apply to insert the templates marked READY above."
        )
        return 0

    ready = [r for r in results if r.status == "ready"]
    if not ready:
        print("\nNo templates are ready to import — nothing applied.")
        return 0

    apply_ready_records(ready)

    print(
        f"\nAPPLIED — inserted {len(ready)} recurring template(s) as new rows "
        f"(new ids assigned by the database). No invoices were generated."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
