"""add invoice activity log

Revision ID: 6cc5ec319b46
Revises: 7b162203112b
Create Date: 2026-03-30 15:01:13.065801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc5ec319b46'
down_revision: Union[str, Sequence[str], None] = '7b162203112b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_label', sa.String(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_activity_logs_entity_id'), 'invoice_activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_invoice_activity_logs_event_type'), 'invoice_activity_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_invoice_activity_logs_id'), 'invoice_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_activity_logs_invoice_id'), 'invoice_activity_logs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_activity_logs_project_id'), 'invoice_activity_logs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_activity_logs_project_id'), table_name='invoice_activity_logs')
    op.drop_index(op.f('ix_invoice_activity_logs_invoice_id'), table_name='invoice_activity_logs')
    op.drop_index(op.f('ix_invoice_activity_logs_id'), table_name='invoice_activity_logs')
    op.drop_index(op.f('ix_invoice_activity_logs_event_type'), table_name='invoice_activity_logs')
    op.drop_index(op.f('ix_invoice_activity_logs_entity_id'), table_name='invoice_activity_logs')
    op.drop_table('invoice_activity_logs')
    # ### end Alembic commands ###
